############################################ 
## R script                               ##
## Project: IL17.TNF_Biologics_manuscript ##
## Supplementary Figures 07 and 08        ##
## 16S data                               ##
## Author: JM                             ##
############################################

### Brief description:
### This script covers the code for Supplementary Figures 07 and 08.

### Supplementary Figure 07:
### Panel A: LEfSe analysis in Candida expanders vs non-expanders pre-IL17i
### Panel B: LEfSe analysis in Candida expanders vs non-expanders IL17i maintenance

### Supplementary Figure 08:
### Panel A: LEfSe analysis in Candida albicans expanders vs non-expanders pre-IL17i
### Panel B: LEfSe analysis in Candida albicans expanders vs non-expanders IL17i maintenance

############################################################################
############################################################################
############################################################################

### Load libraries ###

library(ggplot2)
library(data.table)
library(ggthemes)
library(reshape2)
library(scales)

############################################################################
############################################################################
############################################################################

### LEfSe ###

# Analysis was performed using LEfSe v1.0.7 at IL-17i pre and IL-17i maintenance visits to compare subjects who demonstrated high expansion of Candida or C. albicans versus those who demonstrated modest expansion or contraction.
# High expansion was defined as the top quartile of positive change in relative abundance from pre to maintenance visits.
# Input file included taxa at the genus level and there was no cut-off for relative abundance.
# Output file generated by run_lefse.py command without subclass analysis (.res) was used to create LDA graph (A panels).
# FDR significance calculated using group_significance.py command in QIIME v1.9.1 via Kruksal-Wallis (B panels).

### LEfSe ###

## Setup

# colors
# green: high expansion
# navy: other
col1 <- c("#53d397", "#0c317a")

# background theme
bkg <- theme_classic() +
  theme(axis.text.x = element_text(size = 10, face = "bold", color = "black")) +
  theme(axis.text.y = element_text(size = 8, color = "black")) +
  theme(axis.title.x = element_text(size = 10, color = "black", face = "bold")) +
  theme(axis.title.y = element_text(margin = unit(c(0, 8, 0, 0), "mm"))) +
  theme(legend.text = element_text(size = 8, face = "bold", color = "black")) +
  theme(legend.spacing.x = unit(0.2, "cm")) +
  theme(legend.title = element_blank()) +
  theme(legend.justification = "top")

# directory for storing files
dir = ".../IL17.TNF/16S.ITS/jobs/5_lefse_LDA_R/"

# lefse files
lefse.files <- c("16S_human_IL17.B_genus_ITS_g__Candida_no.empty.OTU.res",
                 "16S_human_IL17.D_genus_ITS_g__Candida_no.empty.OTU.res",
                 "16S_human_IL17.B_genus_ITS_s__Candida_albicans_no.empty.OTU.res",
                 "16S_human_IL17.D_genus_ITS_s__Candida_albicans_no.empty.OTU.res")

lefse.names <- c("16S_human_IL17.B_genus_ITS_g__Candida_no.empty.OTU",
                 "16S_human_IL17.D_genus_ITS_g__Candida_no.empty.OTU",
                 "16S_human_IL17.B_genus_ITS_s__Candida_albicans_no.empty.OTU",
                 "16S_human_IL17.D_genus_ITS_s__Candida_albicans_no.empty.OTU")

###########################

## Plotting

# for each lefse file, create an LDA plot
for (i in seq_along(lefse.files)) {
  
  # read in LEfSe output file
  f = paste(dir, lefse.files[i], sep = "")
  lef <- read.table(f, sep = "\t", header = FALSE)
  
  # change column headings
  colnames(lef) = c("taxa", "log_highest_class_avg", "class", "LDA", "p_value")
  
  # remove all non-significant entries
  lef.subset <- subset(lef, LDA != "NA")
  
  # add column with abridged taxa names
  for (j in 1:nrow(lef.subset)) {
    
    # take the 2 lowest taxa classifications
    s <- lapply(strsplit(as.character(lef.subset[[1]]), '\\.'), tail, n = 2)
    
    # add them as separate columns
    t1 <- s[[j]][1]
    t2 <- s[[j]][2]
    
    lef.subset$taxa_1[j] <- paste(t1)
    if(is.na(t2)) {
      lef.subset$taxa_2[j] <- paste(t1)
      sr <- t1
    }
    else {
      lef.subset$taxa_2[j] <- paste(t2)
      sr <- t2
    }
    
    # use the lowest taxa classification as the shortened taxa name
    sr <- gsub("__c_", "](c)", sr)
    sr <- gsub("__o_", "](o)", sr)
    sr <- gsub("__f_", "](f)", sr)
    sr <- gsub("_c_", "(c)", sr)
    sr <- gsub("_o_", "(o)", sr)
    sr <- gsub("_f_", "(f)", sr)
    sr <- gsub("___", "__[", sr)
    sr <- gsub("UC__", "UC_[", sr)
    sr <- gsub("_$", "]", sr)
    lef.subset$taxa_s[j] <- paste(sr)
  }
  
  # find duplicates of shortened taxa names
  dt <- data.table(lef.subset$taxa_s)
  dup <- unlist(unique(dt[duplicated(dt) | duplicated(dt, fromLast=TRUE)]))
  
  # change names of duplicates to allow for appropriate data plotting
  if (length(dup) > 0) {
    for (j in seq_along(dup)) {
      for (k in 1:nrow(lef.subset)) {
        if (lef.subset$taxa_s[k] == dup[[j]]) {
          lef.subset$taxa_s[k] <- paste(lef.subset$taxa_1[k], lef.subset$taxa_2[k], sep = "|")
        }
      }
    }
  }
  
  # order factor levels for plotting
  lef.subset$taxa_s <- factor(lef.subset$taxa_s, levels = lef.subset$taxa_s[rev(order(lef.subset$class, lef.subset$LDA))])
  
  # plot
  p <- ggplot(data = lef.subset, aes(x = taxa_s, y = LDA, fill = class)) +
    geom_bar(stat = "identity", width = 0.8) +
    coord_flip() +
    scale_fill_manual(values = col1, labels = c("High expansion", "Other")) +
    xlab(NULL) + ylab("\nLDA score (log 10)") +
    bkg
  
  # create filename
  filename_plot = paste(lefse.names[i], "lefse", "LDA.plot.pdf", sep = "_")  
  
  # save plot   
  fp = paste(dir, filename_plot, sep = "")
  
  if (lefse.names[i] == "16S_human_IL17.B_genus_ITS_g__Candida_no.empty.OTU") {
    pdf(file = fp, height = 2.5, width = 6)
  } else if (lefse.names[i] == "16S_human_IL17.D_genus_ITS_g__Candida_no.empty.OTU") {
    pdf(file = fp, height = 5, width = 6)
  } else if (lefse.names[i] == "16S_human_IL17.B_genus_ITS_s__Candida_albicans_no.empty.OTU") {
    pdf(file = fp, height = 2, width = 6)
  } else if (lefse.names[i] == "16S_human_IL17.D_genus_ITS_s__Candida_albicans_no.empty.OTU") {
    pdf(file = fp, height = 4.5, width = 6)
  }
  
  plot(p)
  dev.off()
}

############################################################################
############################################################################
############################################################################

### LEfSe relative abundance ###

# Input files:
# Column 1: SampleID
# Column 2: High expander vs non-high expander
# Remainder of columns: relative abundance across samples for each taxon identified as significant by LEfSe analysis

## Setup

# colors
# green: expansion
# grey: navy
col1 <- c("#53d397", "#0c317a")

# background theme
bkg <- theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 0, size = 14, color = "black")) +
  theme(axis.text.y = element_text(angle = 90, vjust = 0, size = 11, color = "black")) +
  theme(axis.title.y = element_text(angle = 180, hjust = 0, size = 13, color = "black", face = "bold", margin = unit(c(0, 6, 0, 0), "mm"))) +
  theme(legend.text = element_text(size = 8, face = "bold", color = "black")) +
  theme(legend.spacing.x = unit(0.2, "cm")) +
  theme(legend.title = element_blank()) +
  theme(legend.position = "top")

# function for plot
stats.dot.median <- function(x) {
  m <- median(x)
  min <- min(x)
  max <- max(x)
  return(c(y = m, ymin = min, ymax = max))
}

## Plotting

## Candida baseline visit ##

# read in table
d.rel.abund <- read.table(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.B_rev.txt",
                          header = TRUE, row.names = 1, sep = "\t", check.names = FALSE,
                          na.strings = "NA")

# convert to data frame
d.rel.abund <- as.data.frame(d.rel.abund)

# melt data for plotting
d <- melt(d.rel.abund, id = "Candida_expansion")

# plot
p <- ggplot(d, aes(x = variable, y = value, color = Candida_expansion)) +
  geom_hline(yintercept=0, alpha = 0.1) +
  stat_summary(fun.data = stats.dot.median, geom = "pointrange", 
               position = position_dodge(width = 0.5), size = 0.5) +
  scale_color_manual(values = col1, labels = c("High expansion", "Other")) +
  scale_x_discrete(position = "top") +
  # sqrt scale
  scale_y_continuous(trans = sqrt_trans(), position = "right", limits = c(0,0.4)) +
  xlab("") + ylab("") +
  bkg 

# save plot
pdf(file = ".../16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.B_plot_rev.pdf",
    height = 5.5, width = 4)
plot(p)
dev.off()

# save plot stats
s <- aggregate(value ~ variable+Candida_expansion, data = d, stats.dot.median)
s <- t(s)

write.csv(s, file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.B_stats_rev.csv")

###################

## Candida maintenance visit ##

# read in table
d.rel.abund <- read.table(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.D_rev.txt",
                          header = TRUE, row.names = 1, sep = "\t", check.names = FALSE,
                          na.strings = "NA")

# convert to data frame
d.rel.abund <- as.data.frame(d.rel.abund)

# melt data for plotting
d <- melt(d.rel.abund, id = "Candida_expansion")

# plot
p <- ggplot(d, aes(x = variable, y = value, color = Candida_expansion)) +
  geom_hline(yintercept=0, alpha = 0.1) +
  stat_summary(fun.data = stats.dot.median, geom = "pointrange", 
               position = position_dodge(width = 0.5), size = 0.5) +
  scale_color_manual(values = col1, labels = c("High expansion", "Other")) +
  scale_x_discrete(position = "top") +
  # sqrt scale
  scale_y_continuous(trans = sqrt_trans(), position = "right", limits = c(0,0.8)) +
  xlab("") + ylab("") +
  bkg 

# save plot
pdf(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.D_plot_rev.pdf",
    height = 7, width = 9.5)
plot(p)
dev.off()

# save plot stats
s <- aggregate(value ~ variable+Candida_expansion, data = d, stats.dot.median)
s <- t(s)

write.csv(s, file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida_IL17.D_stats_rev.csv")

####################

## Candida albicans baseline visit ##

# read in table
d.rel.abund <- read.table(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.B_rev.txt",
                          header = TRUE, row.names = 1, sep = "\t", check.names = FALSE,
                          na.strings = "NA")

# convert to data frame
d.rel.abund <- as.data.frame(d.rel.abund)

# melt data for plotting
d <- melt(d.rel.abund, id = "Candida.albicans_expansion")

# plot
p <- ggplot(d, aes(x = variable, y = value, color = Candida.albicans_expansion)) +
  geom_hline(yintercept=0, alpha = 0.1) +
  stat_summary(fun.data = stats.dot.median, geom = "pointrange", 
               position = position_dodge(width = 0.5), size = 0.5) +
  scale_color_manual(values = col1, labels = c("High expansion", "Other")) +
  scale_x_discrete(position = "top") +
  # sqrt scale
  scale_y_continuous(trans = sqrt_trans(), position = "right", limits = c(0,0.2)) +
  xlab("") + ylab("") +
  bkg 

# save plot
pdf(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.B_plot_rev.pdf",
    height = 5, width = 3.5)
plot(p)
dev.off()

# save plot stats
s <- aggregate(value ~ variable+Candida.albicans_expansion, data = d, stats.dot.median)
s <- t(s)

write.csv(s, file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.B_stats_rev.csv")

##################

## Candida albicans maintenance visit ##

# read in table
d.rel.abund <- read.table(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.D_rev.txt",
                          header = TRUE, row.names = 1, sep = "\t", check.names = FALSE,
                          na.strings = "NA")

# convert to data frame
d.rel.abund <- as.data.frame(d.rel.abund)

# melt data for plotting
d <- melt(d.rel.abund, id = "Candida.albicans_expansion")

# plot
p <- ggplot(d, aes(x = variable, y = value, color = Candida.albicans_expansion)) +
  geom_hline(yintercept=0, alpha = 0.1) +
  stat_summary(fun.data = stats.dot.median, geom = "pointrange", 
               position = position_dodge(width = 0.5), size = 0.5) +
  scale_color_manual(values = col1, labels = c("High expansion", "Other")) +
  scale_x_discrete(position = "top") +
  # sqrt scale
  scale_y_continuous(trans = sqrt_trans(), position = "right", limits = c(0,0.5)) +
  xlab("") + ylab("") +
  bkg 

# save plot
pdf(file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.D_plot_rev.pdf",
    height = 5.5, width = 6.5)
plot(p)
dev.off()

# save plot stats
s <- aggregate(value ~ variable+Candida.albicans_expansion, data = d, stats.dot.median)
s <- t(s)

write.csv(s, file = ".../IL17.TNF/16S.ITS/jobs/5_lefse.taxa_rel.abund/rel.abund_Candida.albicans_IL17.D_stats_rev.csv")

